pool:
  vmImage: "ubuntu-latest"

variables:
    solution: "Clean-Architecture-Manga.sln"
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    DOTNET_CLI_TELEMETRY_OPTOUT: "true"

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.201
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: "Compile VS solution"
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration "$(buildConfiguration)"

- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(buildConfiguration)'
  inputs:
    command: test
    projects: '$(solution)'
    arguments: '"-p:CollectCoverage=true" "-p:CoverletOutputFormat=cobertura"'
    nobuild: true

- task: CmdLine@2
  displayName: Merge code-coverage files
  inputs:
    script: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator "-reports:./src/**/coverage.cobertura.xml" "-reporttypes:Cobertura" "-targetdir:./coverreport"
    # reportgenerator "-reports:./coverreport/Cobertura.xml" "-reporttypes:Html" "-targetdir:./coverreport"
- task: PublishCodeCoverageResults@1
  displayName: "Generate code-coverage HTML report"
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: './coverreport/Cobertura.xml'
    failIfCoverageEmpty: true
